#!/usr/bin/php

<?php

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$stell = new Application('Stell', '1.0.11');

# All commands
$stell->add(new MakeCommand());

$stell->run();